### ISSUE TITLE
No module named gyp.common error

### ISSUE THREAD

**Issue by dariocravero** [pmq20/node-packer#108]
Hi,

I'm getting this error when trying to run nodec:
```
  File "./configure", line 34, in <module>
    from gyp.common import GetFlavor
ImportError: No module named gyp.common
```

Here's the output of the full process. I've used the sample eggjs project to test it:
```
[master*] $ cd ~/opensource/
opensource $ git clone --depth 1 https://github.com/eggjs/examples.git
Cloning into 'examples'...
remote: Counting objects: 444, done.
remote: Compressing objects: 100% (306/306), done.
remote: Total 444 (delta 64), reused 333 (delta 39), pack-reused 0
Receiving objects: 100% (444/444), 107.49 KiB | 153.00 KiB/s, done.
Resolving deltas: 100% (64/64), done.
opensource $ cd examples/helloworld
helloworld [master] $ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN co-mocha@1.2.1 requires a peer of mocha@>=1.18 <5 but none was installed.

added 884 packages in 23.981s
helloworld [master*] $ nodec node_modules/egg-bin/bin/egg-bin.js
Node.js Compiler (nodec) v1.5.0
- entrance: /Users/craverod/opensource/examples/helloworld/node_modules/egg-bin/bin/egg-bin.js
- options: {:npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"x64", :output=>"/Users/craverod/opensource/examples/helloworld/a.out", :tmpdir=>"/var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec"}

-> mkdir -p /var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec
-> rm -rf /var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec/__work_dir__
-> mkdir -p /var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec/__work_dir__
-> cp -r "/Users/craverod/opensource/examples/helloworld/node_modules/egg-bin" "/var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec/__work_dir__/__enclose_io_memfs__"
-> cd /var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec/__work_dir__/__enclose_io_memfs__
-> Running ["npm -v"]
5.3.0
-> Running ["npm install --production"]
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN egg-bin@4.3.7 No license field.
npm WARN The package semver is included as both a dev and production dependency.

added 683 packages in 21.51s
-> cd /Users/craverod/opensource/examples/helloworld
-> cd /var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec/__work_dir__/__enclose_io_memfs__
-> cd /Users/craverod/opensource/examples/helloworld
-> cd /var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec/node-8.3.0-1.5.0
-> rm -f deps/libsquash/sample/enclose_io_memfs.squashfs
-> rm -f deps/libsquash/sample/enclose_io_memfs.c
-> Running ["mksquashfs -version"]
mksquashfs version 4.3 (2014/05/12)
copyright (C) 2014 Phillip Lougher <phillip@squashfs.org.uk>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
-> Running ["mksquashfs /var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec/__work_dir__ deps/libsquash/sample/enclose_io_memfs.squashfs"]
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on deps/libsquash/sample/enclose_io_memfs.squashfs, block size 131072.
[========================================================|] 11996/11996 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments, no xattrs
	duplicates are removed
Filesystem size 6261.27 Kbytes (6.11 Mbytes)
	18.90% of uncompressed filesystem size (33130.98 Kbytes)
Inode table size 127198 bytes (124.22 Kbytes)
	29.16% of uncompressed inode table size (436214 bytes)
Directory table size 118517 bytes (115.74 Kbytes)
	41.13% of uncompressed directory table size (288131 bytes)
Number of duplicate files found 4983
Number of inodes 13586
Number of files 11983
Number of fragments 149
Number of symbolic links  43
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 1560
Number of ids (unique uids + gids) 2
Number of uids 1
	craverod (1678251129)
Number of gids 1
	unknown (163264107)
-> cd /Users/craverod/opensource/examples/helloworld
-> cd /var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec/node-8.3.0-1.5.0
-> cd /Users/craverod/opensource/examples/helloworld
-> cd /var/folders/wh/418ybxp131d3q0k7cswh6twxk0h53s/T/nodec/node-8.3.0-1.5.0
-> Running ["./configure "]
Traceback (most recent call last):
  File "./configure", line 34, in <module>
    from gyp.common import GetFlavor
ImportError: No module named gyp.common
Failed running ["./configure "]
```

Would you have any hints on what might be wrong? I tried to install `node-gyp` both globally and locally and that didn't make a difference. The version of nodec is the latest and the version of node I'm using is matching it v8.3.0. Here's the output of `npm version` just in case:
```
{ npm: '5.3.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.3.0',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.13.1',
  v8: '6.0.286.52',
  zlib: '1.2.11' }
```

Thanks!

**Comment by xuerongzhao** [comment]
I also encountered the same problem

**Comment by dev-marc-laurent** [comment]
I got the same issue and I solved that by doing the following steps:

1. Ensuring that I have the [setuptools](https://pypi.org/project/setuptools/) and [pip](https://pypi.org/project/pip/) installed
`sudo apt install python-setuptools python-pip`

2. Installing GYP (I followed these steps: https://github.com/mogemimi/pomdog/wiki/How-to-Install-GYP)

I hope this can help.

**Comment by jxycbjhc** [comment]
2020年了，还有老铁预见这种问题吗？
