### ISSUE TITLE
Windows version does not work (Win10, nodec 1.5.0 x64)

### ISSUE THREAD

**Issue by darkguy2008** [pmq20/node-packer#143]
So I downloaded it and I get this:

```
nodec-v1.5.0-x64.exe

C:/__enclose_io_memfs__/local/lib/compiler.rb:105: [BUG] Segmentation fault
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mswin64_140]

-- Control frame information -----------------------------------------------
c:0006 p:---- s:0035 e:000034 CFUNC  :`
c:0005 p:0100 s:0030 e:000027 METHOD C:/__enclose_io_memfs__/local/lib/compiler.rb:105
c:0004 p:0046 s:0024 e:000023 METHOD C:/__enclose_io_memfs__/local/lib/compiler.rb:26 [FINISH]
c:0003 p:---- s:0018 e:000017 CFUNC  :new
c:0002 p:0153 s:0012 E:0013c0 EVAL   /__enclose_io_memfs__/local/bin/nodec:153 [FINISH]
c:0001 p:0000 s:0003 E:001fa0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/__enclose_io_memfs__/local/bin/nodec:153:in `<main>'
/__enclose_io_memfs__/local/bin/nodec:153:in `new'
C:/__enclose_io_memfs__/local/lib/compiler.rb:26:in `initialize'
C:/__enclose_io_memfs__/local/lib/compiler.rb:105:in `init_options'
C:/__enclose_io_memfs__/local/lib/compiler.rb:105:in ``'

-- C level backtrace information -------------------------------------------
C:\Windows\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0x14) [0x00007FFC4BE3C0E4]
C:\Windows\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x93) [0x00007FFC49A38BA3]
 [0x00007FF6E0433934]
 [0x00007FF6E04339B9]
 [0x00007FF6E036AE40]
 [0x00007FF6E03D5026]
C:\Windows\System32\ucrtbase.dll(seh_filter_exe+0x233) [0x00007FFC49D1B7F3]
 [0x00007FF6E04ACB00]
C:\Windows\SYSTEM32\VCRUNTIME140.dll(_C_specific_handler+0xa0) [0x00007FFC3B0FB890]
C:\Windows\SYSTEM32\ntdll.dll(_chkstk+0x11f) [0x00007FFC4BE4119F]
C:\Windows\SYSTEM32\ntdll.dll(RtlRaiseException+0x399) [0x00007FFC4BE0A229]
C:\Windows\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x00007FFC4BE3FE0E]
C:\Windows\SYSTEM32\ntdll.dll(RtlEnterCriticalSection+0x23e) [0x00007FFC4BDBB5CE]
C:\Windows\SYSTEM32\ntdll.dll(RtlEnterCriticalSection+0x40) [0x00007FFC4BDBB3D0]
 [0x00007FF6E0328F92]
 [0x00007FF6E0391F26]
 [0x00007FF6E0397AE6]
 [0x00007FF6E03918CD]
 [0x00007FF6E0391C4B]
 [0x00007FF6E0391FBE]
 [0x00007FF6E0360545]
 [0x00007FF6E0361029]
 [0x00007FF6E0360C4D]
 [0x00007FF6E0363886]
 [0x00007FF6E03625C1]
 [0x00007FF6E035FF36]
 [0x00007FF6E035FCCA]
 [0x00007FF6E035A656]
 [0x00007FF6E035B511]
 [0x00007FF6E037B274]
 [0x00007FF6E0360545]
 [0x00007FF6E0361029]
 [0x00007FF6E0360C4D]
 [0x00007FF6E0363886]
 [0x00007FF6E03625C1]
 [0x00007FF6E030EA5F]
 [0x00007FF6E030EAB9]
 [0x00007FF6E030ED30]
 [0x00007FF6E030111C]
 [0x00007FF6E04ABE59]
C:\Windows\System32\KERNEL32.DLL(BaseThreadInitThunk+0x14) [0x00007FFC4B737BD4]

-- Other runtime information -----------------------------------------------

* Loaded script: /__enclose_io_memfs__/local/bin/nodec

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 encdb.so
    5 trans/transdb.so
    6 enc/windows_1252.so
    7 C:/__enclose_io_memfs__/lib/ruby/2.4.0/unicode_normalize.rb
    8 C:/__enclose_io_memfs__/lib/ruby/2.4.0/x64-mswin64_140/rbconfig.rb
    9 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/compatibility.rb
   10 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/defaults.rb
   11 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/deprecate.rb
   12 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/errors.rb
   13 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/version.rb
   14 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/requirement.rb
   15 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/platform.rb
   16 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/basic_specification.rb
   17 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/stub_specification.rb
   18 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/util/list.rb
   19 stringio.so
   20 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/specification.rb
   21 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/exceptions.rb
   22 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_gem.rb
   23 C:/__enclose_io_memfs__/lib/ruby/2.4.0/monitor.rb
   24 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb
   25 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb
   26 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/dependency.rb
   27 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/path_support.rb
   28 C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb
   29 C:/__enclose_io_memfs__/local/lib/compiler/constants.rb
   30 C:/__enclose_io_memfs__/local/lib/compiler/error.rb
   31 C:/__enclose_io_memfs__/lib/ruby/2.4.0/shellwords.rb
   32 C:/__enclose_io_memfs__/lib/ruby/2.4.0/tmpdir.rb
   33 C:/__enclose_io_memfs__/lib/ruby/2.4.0/open3.rb
   34 C:/__enclose_io_memfs__/local/lib/compiler/utils.rb
   35 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json/version.rb
   36 C:/__enclose_io_memfs__/lib/ruby/2.4.0/ostruct.rb
   37 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json/generic_object.rb
   38 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json/common.rb
   39 json/ext/parser.so
   40 json/ext/generator.so
   41 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json/ext.rb
   42 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json.rb
   43 C:/__enclose_io_memfs__/local/lib/compiler/npm_package.rb
   44 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/rfc2396_parser.rb
   45 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/rfc3986_parser.rb
   46 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/common.rb
   47 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/generic.rb
   48 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ftp.rb
   49 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/http.rb
   50 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/https.rb
   51 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ldap.rb
   52 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ldaps.rb
   53 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/mailto.rb
   54 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri.rb
   55 cgi/escape.so
   56 C:/__enclose_io_memfs__/lib/ruby/2.4.0/cgi/util.rb
   57 strscan.so
   58 C:/__enclose_io_memfs__/lib/ruby/2.4.0/erb.rb
   59 C:/__enclose_io_memfs__/lib/ruby/2.4.0/securerandom.rb
   60 C:/__enclose_io_memfs__/local/lib/compiler.rb
   61 C:/__enclose_io_memfs__/lib/ruby/2.4.0/optparse.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
```

That's too bad though, it looked really promising.

Any pointers?

Thanks!

**Comment by liudonghua123** [comment]
I have the same issue. I use Win 10 1909, and installed python 2.7, visual studio 2017, add nodec and SquashFS path. From the error message, it may have problems with ruby?

```
>nodec
D:/__enclose_io_memfs__/local/lib/compiler.rb:105: [BUG] Segmentation fault
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mswin64_140]

-- Control frame information -----------------------------------------------
c:0006 p:---- s:0035 e:000034 CFUNC  :`
c:0005 p:0100 s:0030 e:000027 METHOD D:/__enclose_io_memfs__/local/lib/compiler.rb:105
c:0004 p:0046 s:0024 e:000023 METHOD D:/__enclose_io_memfs__/local/lib/compiler.rb:26 [FINISH]
c:0003 p:---- s:0018 e:000017 CFUNC  :new
c:0002 p:0153 s:0012 E:000d90 EVAL   /__enclose_io_memfs__/local/bin/nodec:153 [FINISH]
c:0001 p:0000 s:0003 E:002100 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/__enclose_io_memfs__/local/bin/nodec:153:in `<main>'
/__enclose_io_memfs__/local/bin/nodec:153:in `new'
D:/__enclose_io_memfs__/local/lib/compiler.rb:26:in `initialize'
D:/__enclose_io_memfs__/local/lib/compiler.rb:105:in `init_options'
D:/__enclose_io_memfs__/local/lib/compiler.rb:105:in ``'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0x14) [0x00007FFB2615C144]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x93) [0x00007FFB233E8BA3]
 [0x00007FF63DE83934]
 [0x00007FF63DE839B9]
 [0x00007FF63DDBAE40]
 [0x00007FF63DE25026]
C:\WINDOWS\System32\ucrtbase.dll(seh_filter_exe+0x233) [0x00007FFB2331C043]
 [0x00007FF63DEFCB00]
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll(_C_specific_handler+0xa0) [0x00007FFB0DB2C1C0]
C:\WINDOWS\SYSTEM32\ntdll.dll(_chkstk+0x11f) [0x00007FFB261611FF]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlRaiseException+0x399) [0x00007FFB2612A289]
C:\WINDOWS\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x00007FFB2615FE6E]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlEnterCriticalSection+0x23e) [0x00007FFB260DB63E]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlEnterCriticalSection+0x40) [0x00007FFB260DB440]
 [0x00007FF63DD78F92]
 [0x00007FF63DDE1F26]
 [0x00007FF63DDE7AE6]
 [0x00007FF63DDE18CD]
 [0x00007FF63DDE1C4B]
 [0x00007FF63DDE1FBE]
 [0x00007FF63DDB0545]
 [0x00007FF63DDB1029]
 [0x00007FF63DDB0C4D]
 [0x00007FF63DDB3886]
 [0x00007FF63DDB25C1]
 [0x00007FF63DDAFF36]
 [0x00007FF63DDAFCCA]
 [0x00007FF63DDAA656]
 [0x00007FF63DDAB511]
 [0x00007FF63DDCB274]
 [0x00007FF63DDB0545]
 [0x00007FF63DDB1029]
 [0x00007FF63DDB0C4D]
 [0x00007FF63DDB3886]
 [0x00007FF63DDB25C1]
 [0x00007FF63DD5EA5F]
 [0x00007FF63DD5EAB9]
 [0x00007FF63DD5ED30]
 [0x00007FF63DD5111C]
 [0x00007FF63DEFBE59]
C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x14) [0x00007FFB25DC7BD4]

-- Other runtime information -----------------------------------------------

* Loaded script: /__enclose_io_memfs__/local/bin/nodec

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 encdb.so
    5 trans/transdb.so
    6 enc/gbk.so
    7 D:/__enclose_io_memfs__/lib/ruby/2.4.0/unicode_normalize.rb
    8 D:/__enclose_io_memfs__/lib/ruby/2.4.0/x64-mswin64_140/rbconfig.rb
    9 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/compatibility.rb
   10 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/defaults.rb
   11 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/deprecate.rb
   12 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/errors.rb
   13 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/version.rb
   14 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/requirement.rb
   15 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/platform.rb
   16 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/basic_specification.rb
   17 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/stub_specification.rb
   18 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/util/list.rb
   19 stringio.so
   20 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/specification.rb
   21 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/exceptions.rb
   22 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_gem.rb
   23 D:/__enclose_io_memfs__/lib/ruby/2.4.0/monitor.rb
   24 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb
   25 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb
   26 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/dependency.rb
   27 D:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/path_support.rb
   28 D:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb
   29 D:/__enclose_io_memfs__/local/lib/compiler/constants.rb
   30 D:/__enclose_io_memfs__/local/lib/compiler/error.rb
   31 D:/__enclose_io_memfs__/lib/ruby/2.4.0/shellwords.rb
   32 D:/__enclose_io_memfs__/lib/ruby/2.4.0/tmpdir.rb
   33 D:/__enclose_io_memfs__/lib/ruby/2.4.0/open3.rb
   34 D:/__enclose_io_memfs__/local/lib/compiler/utils.rb
   35 D:/__enclose_io_memfs__/lib/ruby/2.4.0/json/version.rb
   36 D:/__enclose_io_memfs__/lib/ruby/2.4.0/ostruct.rb
   37 D:/__enclose_io_memfs__/lib/ruby/2.4.0/json/generic_object.rb
   38 D:/__enclose_io_memfs__/lib/ruby/2.4.0/json/common.rb
   39 json/ext/parser.so
   40 json/ext/generator.so
   41 D:/__enclose_io_memfs__/lib/ruby/2.4.0/json/ext.rb
   42 D:/__enclose_io_memfs__/lib/ruby/2.4.0/json.rb
   43 D:/__enclose_io_memfs__/local/lib/compiler/npm_package.rb
   44 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/rfc2396_parser.rb
   45 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/rfc3986_parser.rb
   46 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/common.rb
   47 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/generic.rb
   48 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ftp.rb
   49 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/http.rb
   50 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/https.rb
   51 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ldap.rb
   52 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ldaps.rb
   53 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/mailto.rb
   54 D:/__enclose_io_memfs__/lib/ruby/2.4.0/uri.rb
   55 cgi/escape.so
   56 D:/__enclose_io_memfs__/lib/ruby/2.4.0/cgi/util.rb
   57 strscan.so
   58 D:/__enclose_io_memfs__/lib/ruby/2.4.0/erb.rb
   59 D:/__enclose_io_memfs__/lib/ruby/2.4.0/securerandom.rb
   60 D:/__enclose_io_memfs__/local/lib/compiler.rb
   61 D:/__enclose_io_memfs__/lib/ruby/2.4.0/optparse.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html


>
```

**Comment by zhex900** [comment]
I have the same issue

**Comment by WxBoxOnline** [comment]
Ditto... same issue.

Is there ANY resolution?

Or is this project now abandoned?
