### ISSUE TITLE
Failed running ["call vcbuild.bat  x64"]

### ISSUE THREAD

**Issue by Bodhivrksa** [pmq20/node-packer#79]
您好！
      我的环境是Windows10，node v4.4.4，SquashFS Tools 4.3，Python  2.7.13，VS2015，当我安装完执行nodec  -v时，显示1.5.0，是否意味着我的nodec安装是没有问题的？
     然后我尝试编译一个简单的js文件，
     执行命令nodec -r E:\hello.js -o hello.exe，
     返回

E:\>nodec -r E:\hello.js -o hello.exe
Node.js Compiler (nodec) v1.5.0
- entrance: not provided, a single Node.js interpreter executable will be produced.
- HINT: call nodec with --help to see more options and use case examples
- options: {:root=>"E:\\hello.js", :output=>"E:/hello.exe", :npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"x64", :tmpdir=>"C:/Users/JOHN/AppData/Local/Temp/nodec"}

=== WARNING ===
Please make sure to have installed the correct version of node in your environment.
It should match the enclosed Node.js runtime version of the compiler.
Expecting v8.3.0; yet got v4.4.4.

-> mkdir -p C:/Users/JOHN/AppData/Local/Temp/nodec
-> cd C:/Users/JOHN/AppData/Local/Temp/nodec/node-8.3.0-1.5.0
-> rm -f Release/obj/node/node_main.obj
-> rm -f Debug/obj/node/node_main.obj
-> cd E:/
-> cd C:/Users/JOHN/AppData/Local/Temp/nodec/node-8.3.0-1.5.0
-> Running ["call vcbuild.bat  x64"]
'vcbuild.bat' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Failed running ["call vcbuild.bat  x64"]

        我查看了C:\Users\JOHN\AppData\Local\Temp\nodec\node-8.3.0-1.5.0文件夹，里面只有一个deps的文件夹，没有vcbuild.bat，请问我这是出了什么问题？
       敬请帮忙
谢谢

**Comment by Bodhivrksa** [comment]
您好！
我看文档的动态图，试着对我的项目yr进行打包，bin/www是我的启动项
执行命令 nodec www

    E:\yr>nodec .\bin\www
    Node.js Compiler (nodec) v1.5.0
    - entrance: E:/yr/bin/www
    - options: {:npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"x64", :output=>"E:/yr/a.exe",   :tmpdir=>"C:/Users/JOHN/AppData/Local/Temp/nodec"}

      === WARNING ===
     Please make sure to have installed the correct version of node in your environment.
     It should match the enclosed Node.js runtime version of the compiler.
     Expecting v8.3.0; yet got v4.4.4.

     -> mkdir -p C:/Users/JOHN/AppData/Local/Temp/nodec
     -> rm -rf C:/Users/JOHN/AppData/Local/Temp/nodec/__work_dir__
     -> mkdir -p C:/Users/JOHN/AppData/Local/Temp/nodec/__work_dir__
     -> cp -r "E:/yr" "C:/Users/JOHN/AppData/Local/Temp/nodec/__work_dir__/__enclose_io_memfs__"
     E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1262:in `mkdir': No such file or directory @  dir_s_mkdir -   C:/Users/JOHN/AppData/Local/Temp/nodec/__work_dir__/__enclose_io_memfs__/node_modules/jade/node_modules/uglify-js/node_modules/yargs/node_modules/cliui/node_modules/center-align/node_modules/align-text/node_modules/kind-of/node_modules/is-buffer/test (Errno::ENOENT)
        from E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1262:in `copy'
        from E:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:415:in `block in copy_entry'

里面报的“No such file or directory”是指什么？
敬请帮忙！
谢谢！

**Comment by Bodhivrksa** [comment]
请问我下载了SquashFS Tools 4.3，然后我是要将这个文件夹放在哪个文件夹下，还是要运行mksquashfs.exe，因为运行，执行的cmd很快就消失了，看不出，执行了什么？
      
      E:\yr>nodec .\package.json -d E:\t
     Node.js Compiler (nodec) v1.5.0
    - entrance: E:/yr/package.json
    - options: {:tmpdir=>"E:/t", :npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"x64",   :output=>"E:/yr/a.exe"}
    === WARNING ===
    Please make sure to have installed the correct version of node in your environment.
    It should match the enclosed Node.js runtime version of the compiler.
    Expecting v8.3.0; yet got v4.4.4.
    -> mkdir -p E:/t
    -> rm -rf E:/t/__work_dir__
    -> mkdir -p E:/t/__work_dir__
   -> cp -r "E:/yr" "E:/t/__work_dir__/__enclose_io_memfs__"
   -> cd E:/t/__work_dir__/__enclose_io_memfs__
    E:\yr>nodec .\package.json -d E:\t
    Node.js Compiler (nodec) v1.5.0
   - entrance: E:/yr/package.json
    - options: {:tmpdir=>"E:/t", :npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"x64",  :output=>"E:/yr/a.exe"}
    === WARNING ===
   Please make sure to have installed the correct version of node in your environment.
   It should match the enclosed Node.js runtime version of the compiler.
   Expecting v8.3.0; yet got v4.4.4.
   -> mkdir -p E:/t
  -> rm -rf E:/t/__work_dir__
   -> mkdir -p E:/t/__work_dir__
   -> cp -r "E:/yr" "E:/t/__work_dir__/__enclose_io_memfs__"
   -> cd E:/t/__work_dir__/__enclose_io_memfs__
    -> Running ["\"npm\" -v"]
    2.15.1
    -> Running ["\"npm\" install --production"]
    node-xlsx@0.7.4 node_modules\node-xlsx
   └── xlsx@0.8.8 (exit-on-epipe@1.0.1, commander@2.11.0, cfb@0.11.1, ssf@0.8.2, adler-32@1.1.0, crc- 32@1.1.0, codepage@1.11.0)
   -> cd E:/yr
   -> cd E:/t/__work_dir__/__enclose_io_memfs__
   -> cd E:/yr
   -> cd E:/t/node-8.3.0-1.5.0
   -> rm -f deps/libsquash/sample/enclose_io_memfs.squashfs
  -> rm -f deps/libsquash/sample/enclose_io_memfs.c
   -> Running ["mksquashfs -version"]
   === HINT ===
   Failed exectuing mksquashfs. Have you installed SquashFS Tools?
  - On Windows, you could download it from     https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip
    - On macOS, you could install by using brew: brew install squashfs
    - On Linux, you could install via apt or yum, or build from source after downloading source from http://squashfs.sourceforge.net/
    E:/__enclose_io_memfs__/local/lib/compiler/utils.rb:32:in `spawn': No such file or directory - mksquashfs -version (Errno::ENOENT)
        from E:/__enclose_io_memfs__/local/lib/compiler/utils.rb:32:in `run'
        from E:/__enclose_io_memfs__/local/lib/compiler.rb:294:in `block in make_enclose_io_memfs'
        from E:/__enclose_io_memfs__/local/lib/compiler/utils.rb:46:in `block in chdir'
        from E:/__enclose_io_memfs__/local/lib/compiler/utils.rb:46:in `chdir'
        from E:/__enclose_io_memfs__/local/lib/compiler/utils.rb:46:in `chdir'
        from E:/__enclose_io_memfs__/local/lib/compiler.rb:290:in `make_enclose_io_memfs'
        from E:/__enclose_io_memfs__/local/lib/compiler.rb:186:in `run!'
        from /__enclose_io_memfs__/local/bin/nodec:154:in `<main>'

**Comment by Bodhivrksa** [comment]
打包成功了，但不知道怎么运行这个a.exe？node a.exe失败，直接点击a.exe，doc窗口一闪而过。无从下手。

**Comment by sankoshine** [comment]
Try to run following code in cmd
```
cd e:\yr
a.exe
```

**Comment by Bodhivrksa** [comment]
@sankoshine 
hi,but I think i am failed,when I packing it,doc is writing

     E:\test\node-8.3.0-1.5.0\deps\v8\include\v8.h(4150): warning C4251: “v8::WasmModuleObjectBuilder::received_buffers_”: class“std::vector<v8::WasmModuleObjectBuilder::Buffer,std::allocator<_Ty>>”需要有 dll 接口由class“v8::WasmModuleObjectBuilder
       ”的客户端使用 [E:\test\node-8.3.0-1.5.0\node.vcxproj]
      src\node_main.cc(37): warning C4101: “autoupdate_result”: 未引用的局部变量 [E:\test\node-8.3.0- 1.5.0\node.vcxproj]
      e:\test\node-8.3.0-1.5.0\src\string_bytes.cc(767): warning C4715: “node::StringBytes::Encode”: 不是所有的控件路径都返 回值 [E:\test\node-8.3.0-1.5.0\node.vcxproj]
     e:\test\node-8.3.0-1.5.0\src\string_bytes.cc(767): warning C4715: “node::StringBytes::Encode”: 不是所有的控件路径都返 回值      [E:\test\node-8.3.0-1.5.0\cctest.vcxproj]
    -> cd E:/official
 and I run the a.exe

    E:\official>a.exe

    E:\official>
