### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bigbenz8** [pmq20/node-packer#86]
Here is my whole complie output : 
-------------------------------------------------------------------------------

D:\nodec_tmp>nodec --npm-package=shadowsocks ssserver -d  d:\nodec_tmp  --clean-tmpdir
Node.js Compiler (nodec) v1.5.0
- entrance: ssserver
- options: {:npm_package=>"shadowsocks", :tmpdir=>"d:/nodec_tmp", :clean_tmpdir=>true, :npm=>"npm", :make_args=>"-j4", :vcbuild_args=>"x64", :output=>"D:/nodec_tmp/a
t"}

=== WARNING ===
Please make sure to have installed the correct version of node in your environment.
It should match the enclosed Node.js runtime version of the compiler.
Expecting v8.3.0; yet got v8.6.0.

-> rm -rf d:/nodec_tmp
-> mkdir -p d:/nodec_tmp
-> cp -r "D:/__enclose_io_memfs__/local/node" "d:/nodec_tmp/node-8.3.0-1.5.0"
-> rm -rf d:/nodec_tmp/shadowsocks-latest
-> mkdir -p d:/nodec_tmp/shadowsocks-latest
-> cd d:/nodec_tmp/shadowsocks-latest
-> cd D:/nodec_tmp
-> rm -rf d:/nodec_tmp/__work_dir__
-> mkdir -p d:/nodec_tmp/__work_dir__
-> cp -r "d:/nodec_tmp/shadowsocks-latest" "d:/nodec_tmp/__work_dir__/__enclose_io_memfs__"
-> cd d:/nodec_tmp/__work_dir__/__enclose_io_memfs__
-> Running ["\"npm\" -v"]
5.3.0
-> Running ["\"npm\" install --production"]
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN __enclose_io_memfs__ No description
npm WARN __enclose_io_memfs__ No repository field.
npm WARN __enclose_io_memfs__ No license field.

added 1 package in 7.674s
-> cd D:/nodec_tmp
-> cd d:/nodec_tmp/__work_dir__/__enclose_io_memfs__
-> cd D:/nodec_tmp
-> cd d:/nodec_tmp/__work_dir__/__enclose_io_memfs__
Detected binaries: {"sslocal"=>"./bin/sslocal", "ssserver"=>"./bin/ssserver"}
Using ssserver at ./bin/ssserver
-> Setting entrance to d:/nodec_tmp/shadowsocks-latest/node_modules/shadowsocks/bin/ssserver
-> cd D:/nodec_tmp
-> cd d:/nodec_tmp/node-8.3.0-1.5.0
-> rm -f deps/libsquash/sample/enclose_io_memfs.squashfs
-> rm -f deps/libsquash/sample/enclose_io_memfs.c
-> Running ["mksquashfs -version"]
mksquashfs version 4.3 (2014/05/12)
copyright (C) 2014 Phillip Lougher <phillip@squashfs.org.uk>

[----------------------------------------------------------]
Compiled by Sebastiaan Ebeltjes @ 2015-06-08 (Domoticx.nl)
Compiled with Cygwin on Windows 8.1, compiler: GCC v4.9.2

This version comes with added support for:
- LZMA v4.65
- LZMA2 (XZ) v5.5.0
- LZO v2.09
- LZ4 r130

Enjoy!

[----------------------------------------------------------]

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
-> Running ["mksquashfs \"d:/nodec_tmp/__work_dir__\" deps/libsquash/sample/enclose_io_memfs.squashfs"]
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on deps/libsquash/sample/enclose_io_memfs.squashfs, block size 131072.
[==========================================================================================================================================|] 51/51 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
        compressed data, compressed metadata, compressed fragments, compressed xattrs
        duplicates are removed
Filesystem size 34.03 Kbytes (0.03 Mbytes)
        19.77% of uncompressed filesystem size (172.10 Kbytes)
Inode table size 708 bytes (0.69 Kbytes)
        34.54% of uncompressed inode table size (2050 bytes)
Directory table size 758 bytes (0.74 Kbytes)
        52.24% of uncompressed directory table size (1451 bytes)
Number of duplicate files found 0
Number of inodes 64
Number of files 51
Number of fragments 2
Number of symbolic links  0
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 13
Number of ids (unique uids + gids) 2
Number of uids 1
        Administrator (197108)
Number of gids 1
        None (197121)
-> cd D:/nodec_tmp
-> cd d:/nodec_tmp/node-8.3.0-1.5.0
-> rm -f Release/obj/node/node_main.obj
-> rm -f Debug/obj/node/node_main.obj
-> cd D:/nodec_tmp
-> cd d:/nodec_tmp/node-8.3.0-1.5.0
-> Running ["call vcbuild.bat  x64"]
Looking for Visual Studio 2017
calling: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\\Auxiliary\Build\vcvarsall.bat" amd64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Found MSVS version 15.0
"C:\Python27\python.exe" configure  --dest-cpu=x64 --tag=
creating icu_config.gypi
* Using ICU in deps/icu-small
creating icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'coverage': 'false',
                 'debug_devtools': 'node',
                 'force_dynamic_crt': 0,
                 'host_arch': 'x64',
                 'icu_data_file': 'icudt59l.dat',
                 'icu_data_in': '..\\..\\deps/icu-small\\source/data/in\\icudt59l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '59',
                 'node_byteorder': 'little',
                 'node_enable_d8': 'false',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_module_version': 57,
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/usr/local',
                 'node_release_urlbase': '',
                 'node_shared': 'false',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_use_bundled_v8': 'true',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'true',
                 'node_use_lttng': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'true',
                 'node_use_v8_platform': 'true',
                 'node_without_node_options': 'false',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'shlib_suffix': 'so.57',
                 'target_arch': 'x64',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_enable_inspector': 1,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_promise_internal_field_count': 1,
                 'v8_random_seed': 0,
                 'v8_trace_maps': 0,
                 'v8_use_snapshot': 'false',
                 'want_separate_host_toolset': 0,
                 'want_separate_host_toolset_mkpeephole': 0}}
creating config.gypi
creating config.mk
Traceback (most recent call last):
  File "configure", line 1417, in <module>
    run_gyp(gyp_args)
  File "tools\gyp_node.py", line 53, in run_gyp
    rc = gyp.main(args)
  File "tools\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "tools\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 2032, in GenerateOutput
    generator_flags))
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 953, in _GenerateProject
    return _GenerateMSBuildProject(project, options, version, generator_flags)
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 3378, in _GenerateMSBuildProject
    project_file_name)
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 2714, in _GetMSBuildGlobalProperties
    _ConfigWindowsTargetPlatformVersion(configuration, version))
  File "tools\gyp\pylib\gyp\generator\msvs.py", line 311, in _ConfigWindowsTargetPlatformVersion
    return names[0]
IndexError: list index out of range
Failed to create vc project files.
Failed running ["call vcbuild.bat  x64"]

**Comment by opohacker** [comment]
@bigbenz8 Hi, have you solved this problem? 
@pmq20 I have the same problem as  @bigbenz8 post, can you help to give some suggestions?

**Comment by vast-z** [comment]
I’ve solved this problem, I forget install win10 sdk....so, i read doc and win8 and win10 need to install the sdk. original. (Visual Studio 2017, any edition (including the Build Tools SKU). Required Components: "MSbuild", "VC++ 2017 v141 toolset" **and one of the Windows SDKs (10 or 8.1)**.).)
