### ISSUE TITLE
Error when attempting to compile my project

### ISSUE THREAD

**Issue by RobiFerentz** [pmq20/node-packer#90]
```
C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1262:in `mkdir': No such file or directory @ dir_s_mkdir - C:/Users/robertf/AppData/Local/Temp/nodec/__work_dir__/__enclose_io_memfs__/node_modules/npm/node_modules/libnpx/node_modules/yargs/node_modules/os-locale/node_modules/execa/node_modules/cross-spawn/node_modules/shebang-command/node_modules/shebang-regex (Errno::ENOENT)
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1262:in `copy'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:415:in `block in copy_entry'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1387:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1390:in `block in wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `each'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1389:in `wrap_traverse'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:412:in `copy_entry'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:390:in `block in cp_r'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1460:in `block in fu_each_src_dest'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1476:in `fu_each_src_dest0'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:1458:in `fu_each_src_dest'
        from C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb:389:in `cp_r'
        from C:/__enclose_io_memfs__/local/lib/compiler/utils.rb:57:in `cp_r'
        from C:/__enclose_io_memfs__/local/lib/compiler.rb:248:in `npm_install'
        from C:/__enclose_io_memfs__/local/lib/compiler.rb:181:in `run!'
        from /__enclose_io_memfs__/local/bin/nodec:154:in `<main>'
```

I get the above when attempting to compile my app. I'm not sure what entity is missing in it's 'ENOENT' error.

**Comment by fersucho** [comment]
Hi Robert,
Maybe it's too late for your question but this may help someone else.
I had the same problem recently. Finally I found that Windows has a limited length of 260 chars for the path and name of a file. I reduced the length of the part under my control and I could generate the EXE.
